### ISSUE TITLE
New Setup

### ISSUE THREAD

**Issue by bughatti** [lcmchris/thesillyhome-addon-repo#20]
Hello, I have just tried to setup your addon.  

What I have
Home Assistant 2022.12.4
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221212.0 - latest

Added your repo
Found the addon under Addons and installed

Mariadb installed on another machine with linuxserver/mariadb
was able to login and create database homeassistant

config is 
  db_password: secret
  db_username: root
  db_host: secret_ip
  db_port: "3306"
  db_database: homeassistant
  db_type: mariadb

Below are the errors I have

`  result.init_unbuffered_query()
  File "/opt/venv/lib/python3.9/site-packages/pymysql/connections.py", line 1173, in init_unbuffered_query
    first_packet = self.connection._read_packet()
  File "/opt/venv/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/opt/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/opt/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'homeassistant.states' doesn't exist")
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py", line 16, in <module>
    parse_data_from_db()
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/parse_data.py", line 73, in parse_data_from_db
    df_all = homedb().get_data()
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/home.py", line 73, in get_data
    for df in pd.read_sql(
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 592, in read_sql
    return pandas_sql.read_query(
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1557, in read_query
    result = self.execute(*args)
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1402, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1365, in execute
    return self._exec_driver_sql(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/opt/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 415, in _query
    conn.query(q, unbuffered=True)
  File "/opt/venv/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/venv/lib/python3.9/site-packages/pymysql/connections.py", line 768, in _read_query_result
    result.init_unbuffered_query()
  File "/opt/venv/lib/python3.9/site-packages/pymysql/connections.py", line 1173, in init_unbuffered_query
    first_packet = self.connection._read_packet()
  File "/opt/venv/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/opt/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/opt/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'homeassistant.states' doesn't exist")
[SQL: SELECT                     state_id,                    entity_id  ,                    state  ,                    last_changed  ,                    last_updated  ,                    old_state_id                 from states                 WHERE entity_id in ('light.master_bathrrom_lights', 'lock.garage', 'binary_sensor.blink_back_garden_motion_detected', 'device_tracker.bophone', 'sensor.openweathermap_temperature')                ORDER BY last_updated DESC LIMIT 100000;]
(Background on this error at: https://sqlalche.me/e/14/f405)
Model generation failed.
Starting frontend on 0.0.0.0:2300
Listening on 0.0.0.0:2300
Process started with -u,/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py
Error: ENOENT: no such file or directory, open '/thesillyhome_src/frontend/static/data/metrics_matrix.json'
    at Object.openSync (node:fs:590:3)
    at readFileSync (node:fs:458:35)
    at get (file:///thesillyhome_src/frontend/build/server/entries/endpoints/Dashboard.ts.js:4:16)
    at render_endpoint (file:///thesillyhome_src/frontend/build/server/index.js:179:26)
    at resolve (file:///thesillyhome_src/frontend/build/server/index.js:2133:31)
    at async respond (file:///thesillyhome_src/frontend/build/server/index.js:2104:22)
    at async Array.ssr (file:///thesillyhome_src/frontend/build/handler-c0fb0568.js:1053:3)
Process started with -u,/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py
Process started with -u,/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py
Process started with -u,/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py
Error: ENOENT: no such file or directory, open '/thesillyhome_src/frontend/static/data/metrics_matrix.json'
    at Object.openSync (node:fs:590:3)
    at readFileSync (node:fs:458:35)
    at get (file:///thesillyhome_src/frontend/build/server/entries/endpoints/Dashboard.ts.js:4:16)
    at render_endpoint (file:///thesillyhome_src/frontend/build/server/index.js:179:26)
    at resolve (file:///thesillyhome_src/frontend/build/server/index.js:2133:31)
    at async respond (file:///thesillyhome_src/frontend/build/server/index.js:2104:22)
    at async Array.ssr (file:///thesillyhome_src/frontend/build/handler-c0fb0568.js:1053:3)
Process started with -u,/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py
Error: ENOENT: no such file or directory, open '/thesillyhome_src/frontend/static/data/metrics_matrix.json'
    at Object.openSync (node:fs:590:3)
    at readFileSync (node:fs:458:35)
    at get (file:///thesillyhome_src/frontend/build/server/entries/endpoints/Dashboard.ts.js:4:16)
    at render_endpoint (file:///thesillyhome_src/frontend/build/server/index.js:179:26)
    at resolve (file:///thesillyhome_src/frontend/build/server/index.js:2133:31)
    at async respond (file:///thesillyhome_src/frontend/build/server/index.js:2104:22)
    at async Array.ssr (file:///thesillyhome_src/frontend/build/handler-c0fb0568.js:1053:3)`

**Comment by bughatti** [comment]
`MariaDB [homeassistant]> show tables;
Empty set (0.001 sec)`

**Comment by lcmchris** [comment]
Hi @bughatti, it is one of the dependencies as that's where the data is coming from!

**Comment by bughatti** [comment]
will setting this up mess with anything i already have and currently running?

**Comment by lcmchris** [comment]
Hi @bughatti - I actually deployed a new version literally just now that should make it work with the default sqlite Home assistant db! 
In your config, you can use now: 
- db_type: sqlite
- db_database: home-assistant_v2.db

**Comment by lcmchris** [comment]
If you upgrade to the latest addon version and just have the 2 lines there for the db config it should work!

**Comment by bughatti** [comment]
- db_database: home-assistant_v2.db
  db_type: sqlite



Starting to parse DB data
2022-12-19 16:52:50,206 - root - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py", line 14, in <module>
    base_config_checks()
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/config_checker.py", line 6, in base_config_checks
    check_mandatory_fields(
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/config_checker.py", line 32, in check_mandatory_fields
    raise KeyError(
KeyError: 'Missing Mandatory field db_password, please add this to the config file.'
Model generation failed.
Starting frontend on 0.0.0.0:2300

**Comment by bughatti** [comment]
Seems to be working now, below is my config.

- db_password: secret
  db_username: hassio
  db_host: xxx.xxx.xxx.xxx
  db_port: "3306"
  db_database: home-assistant_v2.db
  db_type: sqlite

`Starting to parse DB data
2022-12-19 18:12:13,049 - root - INFO - Reading from homedb...
2022-12-19 18:12:13,068 - root - INFO - Getting data from internal homeassistant db
2022-12-19 18:12:13,068 - root - INFO - Executing query
2022-12-19 18:12:16,532 - root - INFO - ['light.master_bathrrom_lights']
2022-12-19 18:12:16,533 - root - INFO - ['lock.garage', 'binary_sensor.blink_back_garden_motion_detected', 'device_tracker.bophone', 'sensor.openweathermap_temperature']
2022-12-19 18:12:16,563 - root - INFO - Add previous state...
2022-12-19 18:12:16,567 - root - INFO - Start parallelization processing...
2022-12-19 18:12:16,841 - root - INFO - Training model for light.master_bathrrom_lights
2022-12-19 18:12:16,849 - root - INFO - ---Training samples = 311
2022-12-19 18:12:16,850 - root - INFO - ---Running training for DecisionTreeClassifier
2022-12-19 18:12:16,850 - root - INFO - -----Model Kwargs = {}
2022-12-19 18:12:17,927 - root - INFO - ---Running training for LogisticRegression
2022-12-19 18:12:17,928 - root - INFO - -----Model Kwargs = {'max_iter': 10000}
2022-12-19 18:12:18,017 - root - INFO - ---Running training for RandomForestClassifier
2022-12-19 18:12:18,018 - root - INFO - -----Model Kwargs = {}
2022-12-19 18:12:18,490 - root - INFO - ---Running training for SVMClassifier
2022-12-19 18:12:18,490 - root - INFO - -----Model Kwargs = {'probability': True}
2022-12-19 18:12:19,292 - root - INFO - Completed!
2022-12-19 18:12:19,305 - root - INFO - Runnining cron with cadence 0 0 * * 0
Starting Appdaemon
Starting frontend on 0.0.0.0:2300
Listening on 0.0.0.0:2300
2022-12-20 01:12:20.587469 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-12-20 01:12:20.587663 INFO AppDaemon: Python version is 3.9.16
2022-12-20 01:12:20.587793 INFO AppDaemon: Configuration read from: /thesillyhome_src/appdaemon/appdaemon.yaml
2022-12-20 01:12:20.587911 INFO AppDaemon: Added log: AppDaemon
2022-12-20 01:12:20.588044 INFO AppDaemon: Added log: Error
2022-12-20 01:12:20.588155 INFO AppDaemon: Added log: Access
2022-12-20 01:12:20.588256 INFO AppDaemon: Added log: Diag
2022-12-20 01:12:20.620318 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2022-12-20 01:12:20.805603 INFO HASS: HASS Plugin Initializing
2022-12-20 01:12:20.805887 INFO HASS: HASS Plugin initialization complete
2022-12-20 01:12:20.806459 INFO AppDaemon: HTTP is disabled
2022-12-20 01:12:20.822821 INFO HASS: Connected to Home Assistant 2022.12.7
2022-12-20 01:12:20.836947 INFO AppDaemon: App 'model_executor' added
2022-12-20 01:12:20.840127 INFO AppDaemon: Found 1 total apps
2022-12-20 01:12:20.840854 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2022-12-20 01:12:20.886653 INFO HASS: Evaluating startup conditions
2022-12-20 01:12:20.896064 INFO HASS: Startup condition met: hass state=RUNNING
2022-12-20 01:12:20.896404 INFO HASS: All startup conditions met
2022-12-20 01:12:20.955544 INFO AppDaemon: Got initial state from namespace default
2022-12-20 01:12:22.846426 INFO AppDaemon: Scheduler running in realtime
2022-12-20 01:12:22.849310 INFO AppDaemon: Adding /thesillyhome_src/appdaemon/apps to module import path
2022-12-20 01:12:22.851278 INFO AppDaemon: Loading App Module: /thesillyhome_src/appdaemon/apps/model_executor.py
2022-12-20 01:12:23.265175 INFO AppDaemon: Initializing app model_executor using class ModelExecutor from module model_executor
2022-12-20 01:12:24.501292 INFO model_executor: Initialized rules engine DB
2022-12-20 01:12:24.591953 INFO model_executor: Hello from TheSillyHome
2022-12-20 01:12:24.597328 INFO model_executor: TheSillyHome Model Executor fully initialized!
2022-12-20 01:12:24.598948 INFO AppDaemon: App initialization complete
Process started with -u,/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py
2022-12-19 18:13:02,557 - root - INFO - Reading from homedb...
2022-12-19 18:13:02,573 - root - INFO - Getting data from internal homeassistant db
2022-12-19 18:13:02,573 - root - INFO - Executing query
2022-12-19 18:13:03,229 - root - INFO - ['light.master_bathrrom_lights']
2022-12-19 18:13:03,230 - root - INFO - ['lock.garage', 'binary_sensor.blink_back_garden_motion_detected', 'device_tracker.bophone', 'sensor.openweathermap_temperature']
2022-12-19 18:13:03,258 - root - INFO - Add previous state...
2022-12-19 18:13:03,261 - root - INFO - Start parallelization processing...
2022-12-19 18:13:03,560 - root - INFO - Training model for light.master_bathrrom_lights
2022-12-19 18:13:03,570 - root - INFO - ---Training samples = 311
2022-12-19 18:13:03,571 - root - INFO - ---Running training for DecisionTreeClassifier
2022-12-19 18:13:03,571 - root - INFO - -----Model Kwargs = {}
2022-12-19 18:13:04,914 - root - INFO - ---Running training for LogisticRegression
2022-12-19 18:13:04,915 - root - INFO - -----Model Kwargs = {'max_iter': 10000}
2022-12-19 18:13:04,995 - root - INFO - ---Running training for RandomForestClassifier
2022-12-19 18:13:04,995 - root - INFO - -----Model Kwargs = {}
2022-12-19 18:13:05,413 - root - INFO - ---Running training for SVMClassifier
2022-12-19 18:13:05,413 - root - INFO - -----Model Kwargs = {'probability': True}
2022-12-19 18:13:06,206 - root - INFO - Completed!
2022-12-19 18:13:06,219 - root - INFO - Runnining cron with cadence 0 0 * * 0
Process started with -u,/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py
2022-12-19 18:13:10,052 - root - INFO - Reading from homedb...
2022-12-19 18:13:10,067 - root - INFO - Getting data from internal homeassistant db
2022-12-19 18:13:10,067 - root - INFO - Executing query
2022-12-19 18:13:10,660 - root - INFO - ['light.master_bathrrom_lights']
2022-12-19 18:13:10,660 - root - INFO - ['lock.garage', 'binary_sensor.blink_back_garden_motion_detected', 'device_tracker.bophone', 'sensor.openweathermap_temperature']
2022-12-19 18:13:10,686 - root - INFO - Add previous state...
2022-12-19 18:13:10,690 - root - INFO - Start parallelization processing...
2022-12-19 18:13:10,947 - root - INFO - Training model for light.master_bathrrom_lights
2022-12-19 18:13:10,954 - root - INFO - ---Training samples = 311
2022-12-19 18:13:10,954 - root - INFO - ---Running training for DecisionTreeClassifier
2022-12-19 18:13:10,954 - root - INFO - -----Model Kwargs = {}
2022-12-19 18:13:12,455 - root - INFO - ---Running training for LogisticRegression
2022-12-19 18:13:12,455 - root - INFO - -----Model Kwargs = {'max_iter': 10000}
2022-12-19 18:13:12,523 - root - INFO - ---Running training for RandomForestClassifier
2022-12-19 18:13:12,523 - root - INFO - -----Model Kwargs = {}
2022-12-19 18:13:12,937 - root - INFO - ---Running training for SVMClassifier
2022-12-19 18:13:12,937 - root - INFO - -----Model Kwargs = {'probability': True}
2022-12-19 18:13:13,808 - root - INFO - Completed!
2022-12-19 18:13:13,820 - root - INFO - Runnining cron with cadence 0 0 * * 0

The website I go to only shows the light I have in my config, not the other 3 things`

**Comment by lcmchris** [comment]
Hi @bughatti - The other 3 are listed as a sensor so they wouldn't appear on the Web UI. Feel free to add a few more actuators though! 
I will close the issue now but let me know if you face any other issues. I am much more active on [discord ](https://discord.gg/haVav7uXm8)if you have quick questions too.
