### ISSUE TITLE
thesillyhome addon cloud - Model generation failed

### ISSUE THREAD

**Issue by simonepittis** [lcmchris/thesillyhome-addon-repo#27]
thesillyhome addon cloud - v 0.0.1

Starting to parse DB data
INFO:root:<---Starting the parsing sequence--->
2023-02-04 16:32:35,320 - root - INFO - <---Starting the parsing sequence--->
INFO:root:Querying data from internal homeassistant db.
2023-02-04 16:32:35,321 - root - INFO - Querying data from internal homeassistant db.
ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py", line 22, in <module>
    homedb().send_data()
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/parse_data.py", line 68, in send_data
    new_last_updated_date = res.scalar_one().replace(tzinfo=timezone.utc)
AttributeError: 'NoneType' object has no attribute 'replace'
2023-02-04 16:32:36,667 - root - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py", line 22, in <module>
    homedb().send_data()
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/parse_data.py", line 68, in send_data
    new_last_updated_date = res.scalar_one().replace(tzinfo=timezone.utc)
AttributeError: 'NoneType' object has no attribute 'replace'
Model generation failed.

**Comment by lcmchris** [comment]
Hi @simonepittis,
Thanks for raising this. The same issue was raised on discord. This is due to a new [update on the HA schema](https://developers.home-assistant.io/blog/2023/01/02/db-schema-v32/).

Working on a fix.

**Comment by lcmchris** [comment]
This should be fixed. Feel free to retest.
