### ISSUE TITLE
tested and got errors

### ISSUE THREAD

**Issue by lotohov** [lcmchris/thesillyhome-addon-repo#3]
2022-05-13 14:46:53.067061 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:46:53.076542 WARNING model_executor: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/appdaemon/apps/model_executor.py", line 49, in state_handler
    if (sensor + "_" + true_state) in df_sen_states.columns:
TypeError: can only concatenate str (not "NoneType") to str
2022-05-13 14:46:53.077932 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:48:46.973747 INFO model_executor: binary_sensor.motion_sensor_158d0001e163f6 is off
2022-05-13 14:48:47.063828 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:48:47.067496 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-05-13 14:48:47.071719 WARNING model_executor: Worker Ags: {'id': 'aec6536480c94565ad1addb89664e812', 'name': 'model_executor', 'objectid': 'f3ee871b007144678c5e02fbd08e339f', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7f789e0610>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d0001e163f6', 'new_state': 'off', 'old_state': 'on', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-05-13 14:48:47.073454 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:48:47.075359 WARNING model_executor: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/appdaemon/apps/model_executor.py", line 49, in state_handler
    if (sensor + "_" + true_state) in df_sen_states.columns:
TypeError: can only concatenate str (not "NoneType") to str
2022-05-13 14:48:47.076601 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:48:49.520628 INFO model_executor: binary_sensor.motion_sensor_158d000405931b is off
2022-05-13 14:48:49.582679 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:48:49.583728 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-05-13 14:48:49.585283 WARNING model_executor: Worker Ags: {'id': 'aec6536480c94565ad1addb89664e812', 'name': 'model_executor', 'objectid': 'f3ee871b007144678c5e02fbd08e339f', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7f789e0610>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d000405931b', 'new_state': 'off', 'old_state': 'on', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-05-13 14:48:49.586661 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:48:49.590855 WARNING model_executor: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/appdaemon/apps/model_executor.py", line 49, in state_handler
    if (sensor + "_" + true_state) in df_sen_states.columns:
TypeError: can only concatenate str (not "NoneType") to str
2022-05-13 14:48:49.591806 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:48:52.646275 INFO model_executor: binary_sensor.motion_sensor_158d0000f461c1 is off
2022-05-13 14:48:52.708525 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:48:52.709363 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-05-13 14:48:52.711081 WARNING model_executor: Worker Ags: {'id': 'aec6536480c94565ad1addb89664e812', 'name': 'model_executor', 'objectid': 'f3ee871b007144678c5e02fbd08e339f', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7f789e0610>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d0000f461c1', 'new_state': 'off', 'old_state': 'on', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-05-13 14:48:52.712393 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:48:52.713839 WARNING model_executor: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/appdaemon/apps/model_executor.py", line 49, in state_handler
    if (sensor + "_" + true_state) in df_sen_states.columns:
TypeError: can only concatenate str (not "NoneType") to str
2022-05-13 14:48:52.714748 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:52:17.191740 INFO model_executor: binary_sensor.motion_sensor_158d000405931b is on
2022-05-13 14:52:17.396325 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:52:17.399561 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-05-13 14:52:17.401960 WARNING model_executor: Worker Ags: {'id': 'aec6536480c94565ad1addb89664e812', 'name': 'model_executor', 'objectid': 'f3ee871b007144678c5e02fbd08e339f', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7f789e0610>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d000405931b', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-05-13 14:52:17.404599 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:52:17.407698 WARNING model_executor: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/appdaemon/apps/model_executor.py", line 49, in state_handler
    if (sensor + "_" + true_state) in df_sen_states.columns:
TypeError: can only concatenate str (not "NoneType") to str
2022-05-13 14:52:17.410469 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:52:20.827055 INFO model_executor: binary_sensor.motion_sensor_158d0000f461c1 is on
2022-05-13 14:52:20.988936 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:52:20.993888 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-05-13 14:52:21.010904 WARNING model_executor: Worker Ags: {'id': 'aec6536480c94565ad1addb89664e812', 'name': 'model_executor', 'objectid': 'f3ee871b007144678c5e02fbd08e339f', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7f789e0610>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d0000f461c1', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-05-13 14:52:21.023520 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:52:21.026209 WARNING model_executor: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/appdaemon/apps/model_executor.py", line 49, in state_handler
    if (sensor + "_" + true_state) in df_sen_states.columns:
TypeError: can only concatenate str (not "NoneType") to str
2022-05-13 14:52:21.035738 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:54:16.893576 INFO model_executor: binary_sensor.motion_sensor_158d000405931b is off
2022-05-13 14:54:16.967735 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:54:16.969133 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-05-13 14:54:16.970424 WARNING model_executor: Worker Ags: {'id': 'aec6536480c94565ad1addb89664e812', 'name': 'model_executor', 'objectid': 'f3ee871b007144678c5e02fbd08e339f', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7f789e0610>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d000405931b', 'new_state': 'off', 'old_state': 'on', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-05-13 14:54:16.971616 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:54:16.973187 WARNING model_executor: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/appdaemon/apps/model_executor.py", line 49, in state_handler
    if (sensor + "_" + true_state) in df_sen_states.columns:
TypeError: can only concatenate str (not "NoneType") to str
2022-05-13 14:54:16.974509 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:54:20.619086 INFO model_executor: binary_sensor.motion_sensor_158d0000f461c1 is off
2022-05-13 14:54:20.742148 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:54:20.743833 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-05-13 14:54:20.745577 WARNING model_executor: Worker Ags: {'id': 'aec6536480c94565ad1addb89664e812', 'name': 'model_executor', 'objectid': 'f3ee871b007144678c5e02fbd08e339f', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7f789e0610>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d0000f461c1', 'new_state': 'off', 'old_state': 'on', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-05-13 14:54:20.748206 WARNING model_executor: ------------------------------------------------------------
2022-05-13 14:54:20.750578 WARNING model_executor: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/appdaemon/apps/model_executor.py", line 49, in state_handler
    if (sensor + "_" + true_state) in df_sen_states.columns:
TypeError: can only concatenate str (not "NoneType") to str
2022-05-13 14:54:20.752069 WARNING model_executor: ------------------------------------------------------------

**Comment by lcmchris** [comment]
Hi @lotohov 
Can this be closed? I think the current master has this issue resolved.

**Comment by lcmchris** [comment]
Will close this for now. Please re-open if this affects you again.
