### ISSUE TITLE
cant update

### ISSUE THREAD

**Issue by lotohov** [lcmchris/thesillyhome-addon-repo#5]
got this in logs
[547446979360] Error updating thesillyhome addon: Can't install lcmchris1/aarch64-thesillyhome:1.0.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=1.0.2&fromImage=lcmchris1%2Faarch64-thesillyhome&platform=linux%2Farm64: Not Found ("manifest for lcmchris1/aarch64-thesillyhome:1.0.2 not found: manifest unknown: manifest unknown")

**Comment by lotohov** [comment]
> [547446979360] Error updating thesillyhome addon: Can't install lcmchris1/aarch64-thesillyhome:1.0.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=1.0.2&fromImage=lcmchris1%2Faarch64-thesillyhome&platform=linux%2Farm64: Not Found ("manifest for lcmchris1/aarch64-thesillyhome:1.0.2 not found: manifest unknown: manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 47, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install lcmchris1/aarch64-thesillyhome:1.0.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=1.0.2&fromImage=lcmchris1%2Faarch64-thesillyhome&platform=linux%2Farm64: Not Found ("manifest for lcmchris1/aarch64-thesillyhome:1.0.2 not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating thesillyhome addon: Can't install lcmchris1/aarch64-thesillyhome:1.0.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=1.0.2&fromImage=lcmchris1%2Faarch64-thesillyhome&platform=linux%2Farm64: Not Found ("manifest for lcmchris1/aarch64-thesillyhome:1.0.2 not found: manifest unknown: manifest unknown")

**Comment by lcmchris** [comment]
Thanks for raising this @lotohov . I was trying to create the new build that should fix you old issue but my laptop is struggling to handle the spanish heat. Promise a fix when I get back to UK by the end of the week!

**Comment by lcmchris** [comment]
Thinking about this now - I will try to maintain future changes in a dev repo (similar to the mqtt addon) just so that I won't break the build!

**Comment by lcmchris** [comment]
@lotohov this should now be working now!
