### ISSUE TITLE
still got errors

### ISSUE THREAD

**Issue by lotohov** [lcmchris/thesillyhome-addon-repo#8]
```
2022-06-23 19:42:13.413825 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:42:13.415450 WARNING model_executor: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 78, in state_handler
    last_state = last_states[device]["state"]
KeyError: 'switch.wall_switch_Left_158d0001308105'
2022-06-23 19:42:13.416173 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:42:13.639798 INFO model_executor: <--- binary_sensor.motion_sensor_158d000405931b is on --->
2022-06-23 19:42:13.773161 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:42:13.774408 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-06-23 19:42:13.775812 WARNING model_executor: Worker Ags: {'id': 'c8256b1289494666bea5cb5719e1cbe9', 'name': 'model_executor', 'objectid': '546c6c8d7a1f40ea902e26bc77e29a5c', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7fa8ea6250>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d000405931b', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-06-23 19:42:13.778951 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:42:13.781647 WARNING model_executor: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 78, in state_handler
    last_state = last_states[device]["state"]
KeyError: 'switch.wall_switch_Left_158d0001308105'
2022-06-23 19:42:13.782482 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:47:16.232909 INFO model_executor: <--- binary_sensor.motion_sensor_158d000405931b is off --->
2022-06-23 19:47:16.302016 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:47:16.304377 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-06-23 19:47:16.307059 WARNING model_executor: Worker Ags: {'id': 'c8256b1289494666bea5cb5719e1cbe9', 'name': 'model_executor', 'objectid': '546c6c8d7a1f40ea902e26bc77e29a5c', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7fa8ea6250>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d000405931b', 'new_state': 'off', 'old_state': 'on', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-06-23 19:47:16.308440 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:47:16.309902 WARNING model_executor: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 78, in state_handler
    last_state = last_states[device]["state"]
KeyError: 'switch.wall_switch_Left_158d0001308105'
2022-06-23 19:47:16.311690 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:48:27.074956 INFO model_executor: <--- binary_sensor.motion_sensor_158d0001e163f6 is off --->
2022-06-23 19:48:27.131741 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:48:27.133140 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-06-23 19:48:27.133910 WARNING model_executor: Worker Ags: {'id': 'c8256b1289494666bea5cb5719e1cbe9', 'name': 'model_executor', 'objectid': '546c6c8d7a1f40ea902e26bc77e29a5c', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7fa8ea6250>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d0001e163f6', 'new_state': 'off', 'old_state': 'on', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-06-23 19:48:27.134581 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:48:27.136765 WARNING model_executor: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 78, in state_handler
    last_state = last_states[device]["state"]
KeyError: 'switch.wall_switch_Left_158d0001308105'
2022-06-23 19:48:27.137335 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:50:34.467084 INFO model_executor: <--- binary_sensor.motion_sensor_158d0000f461c1 is off --->
2022-06-23 19:50:34.567492 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:50:34.568830 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-06-23 19:50:34.570234 WARNING model_executor: Worker Ags: {'id': 'c8256b1289494666bea5cb5719e1cbe9', 'name': 'model_executor', 'objectid': '546c6c8d7a1f40ea902e26bc77e29a5c', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7fa8ea6250>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d0000f461c1', 'new_state': 'off', 'old_state': 'on', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-06-23 19:50:34.571931 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:50:34.573957 WARNING model_executor: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 78, in state_handler
    last_state = last_states[device]["state"]
KeyError: 'switch.wall_switch_Left_158d0001308105'
2022-06-23 19:50:34.575272 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:53:14.461344 INFO model_executor: <--- binary_sensor.motion_sensor_158d0000f461c1 is on --->
2022-06-23 19:53:14.665860 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:53:14.668428 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-06-23 19:53:14.671061 WARNING model_executor: Worker Ags: {'id': 'c8256b1289494666bea5cb5719e1cbe9', 'name': 'model_executor', 'objectid': '546c6c8d7a1f40ea902e26bc77e29a5c', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7fa8ea6250>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d0000f461c1', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-06-23 19:53:14.673140 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:53:14.675692 WARNING model_executor: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 78, in state_handler
    last_state = last_states[device]["state"]
KeyError: 'switch.wall_switch_Left_158d0001308105'
2022-06-23 19:53:14.677868 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:55:14.191575 INFO model_executor: <--- binary_sensor.motion_sensor_158d0000f461c1 is off --->
2022-06-23 19:55:14.480872 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:55:14.483765 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-06-23 19:55:14.486604 WARNING model_executor: Worker Ags: {'id': 'c8256b1289494666bea5cb5719e1cbe9', 'name': 'model_executor', 'objectid': '546c6c8d7a1f40ea902e26bc77e29a5c', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7fa8ea6250>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d0000f461c1', 'new_state': 'off', 'old_state': 'on', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-06-23 19:55:14.488747 WARNING model_executor: ------------------------------------------------------------
2022-06-23 19:55:14.491354 WARNING model_executor: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 78, in state_handler
    last_state = last_states[device]["state"]
KeyError: 'switch.wall_switch_Left_158d0001308105'
2022-06-23 19:55:14.493871 WARNING model_executor: ------------------------------------------------------------
2022-06-23 20:02:41.134590 INFO model_executor: <--- binary_sensor.motion_sensor_158d0000f461c1 is on --->
2022-06-23 20:02:41.257815 WARNING model_executor: ------------------------------------------------------------
2022-06-23 20:02:41.259722 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-06-23 20:02:41.261536 WARNING model_executor: Worker Ags: {'id': 'c8256b1289494666bea5cb5719e1cbe9', 'name': 'model_executor', 'objectid': '546c6c8d7a1f40ea902e26bc77e29a5c', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7fa8ea6250>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d0000f461c1', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-06-23 20:02:41.263326 WARNING model_executor: ------------------------------------------------------------
2022-06-23 20:02:41.265706 WARNING model_executor: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 78, in state_handler
    last_state = last_states[device]["state"]
KeyError: 'switch.wall_switch_Left_158d0001308105'
2022-06-23 20:02:41.267410 WARNING model_executor: ------------------------------------------------------------
```

**Comment by lcmchris** [comment]
Hi @lotohov 
Is there any chance you can share your homeassistant.states db? That would really help me triage your issues.
last_states here is returned by the appdaemon.get_states() which returns all states of live devices. The error here indicates to me that the 'switch.wall_switch_Left_158d0001308105' detailed in the config is not an actual entity id.

Next sprint is where I'll add more logging and testing so hopefully itll be more evident when issues appear.

**Comment by lotohov** [comment]
and you alredy have my states.db ) in PM on forum hass

**Comment by lcmchris** [comment]
Thanks @lotohov , didn't notice the PM!
I don't see anything obvious right now. Intend to add more logging and checks to help examine this so might need a new version.
